site_name: Documentation Nova-Life
site_url: https://aarnow.github.io/NovaLife_Documentation/
repo_name: Aarnow/NovaLife_Documentation
repo_url: https://github.com/Aarnow/NovaLife_Documentation
theme:
  language: fr
  name: material
  logo: assets/logo-mod-white.png
  favicon: assets/favicon-mod-white-128x128.ico
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    tag:
      ui-panel: fontawesome/solid/screwdriver-wrench
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mode sombre
      primary: indigo
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mode clair
      primary: indigo
      accent: indigo

nav:
  - Accueil: index.md
  - Getting Started:
    - Installation: getting-started/installation.md


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/8j2suEE9Mf
  tags:
    UIPanel: ui-panel
  version:
    provider: mike

plugins:
  - tags
  - search

copyright: "Tous droits réservés &copy; 2025 Association MOD"